#!/bin/bash

set -ex

# jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.38 --minimize=False

# Setup a workspace
# jupyter lab workspaces import workspace.json  -- failed
jupyter lab workspaces import binder/workspace.json
