#!/bin/bash

set -ex

# jupyter contrib nbextension install --user
# jupyter nbextension enable --py widgetsnbextension

# takes 1 minute: jupyter labextension install @jupyter-widgets/jupyterlab-manager --minimize=False

# Setup a workspace
# jupyter lab workspaces import workspace.json  -- failed
jupyter lab workspaces import binder/workspace.json
